import CalculatorTemplate from '@/components/features/calculator';
import Head from 'next/head';

export default function Calculator() {
  return (
    <>
      <Head>
        <title>計算 | cat-utils</title>
        <meta name='description' content='Generated by create next app' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, maximum-scale=1.0'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <CalculatorTemplate />
    </>
  );
}
